### ISSUE TITLE
Can B2C be done with no Blazor Server only AzFn API?

### ISSUE THREAD

**Issue by OzBob** [damienbod/PwaBlazorBffAzureB2C#9]
I'm looking at this and https://github.com/login?return_to=%2Fdamienbod%2FBlazor.BFF.AzureB2C.Template,...
there are client+server+b2c solutions and examples, but is there a Static Web blazor client *only* solution to using B2C? 
WASM with only an AzFn API backend and without a hosted blazor/core server?

The cost of static web and AzFn is very low, then add on the need to host a Blazor aspnet.core server and the solution cost is much higher.

**Comment by damienbod** [comment]
Hi @OzBob 

It could be done, but I would not recommend it because you would have to use tokens and store them in the browser.

The recommended way to secure web applications is to use a http only secure cookie. You cannot secure a SPA standalone in this way. 

I would use an App Service with a .NET backend to implement the security. BFF pattern with WASM.

If you use one App Plan (linux) for both apps, the cost should be about the same in Azure.

Here's a template for getting started:

https://www.nuget.org/packages/Blazor.BFF.AzureB2C.Template

Greetings Damien

**Comment by OzBob** [comment]
Thanks @damienbod. Considering the necessity for a hosted backend, I am now more likely to drop wasm and go with server blazor. As I am presuming there are less implementation secrets shared on the browser client.

I will give that template a go. Thx again.
